export const trainingData = [
    {
      day: 1,
      exercises: [
        { name: "Extensión de cuadriceps individual", sessions: [false, false, false, false], repetitions: "3x20" },
        { name: "Extensión de cuadriceps p/juntas", sessions: [false, false, false, false], repetitions: "30,25,20,15" },
        { name: "Sentadilla en Smith o péndulo", sessions: [false, false, false, false], repetitions: "15,12,10,8" },
        { name: "Leg press", sessions: [false, false, false, false], repetitions: "25,20,15,12" },
        { name: "Pantorrilla en prensa", sessions: [false, false, false, false], repetitions: "4x25" },
        { name: "Elevación lateral sentado", sessions: [false, false, false, false], repetitions: "4x20" },
        { name: "Press militar con mancuernas", sessions: [false, false, false, false], repetitions: "15,12,10,8" },
        { name: "Elevación frontal con barra, prono", sessions: [false, false, false, false], repetitions: "4x12" },
      ],
    },
    {
      day: 2,
      exercises: [
        { name: "Encogimiento de rodillas en banco", sessions: [false, false, false, false], repetitions: "4x20" },
        { name: "Crunches sentado", sessions: [false, false, false, false], repetitions: "4x25" },
        { name: "Peso muerto", sessions: [false, false, false, false], repetitions: "15,12,10,10" },
        { name: "Dominadas agarre prono", sessions: [false, false, false, false], repetitions: "50 repeticiones" },
        { name: "Polea al pecho agarre neutro", sessions: [false, false, false, false], repetitions: "12,12,10,8" },
        { name: "Remo en banco agarre supino", sessions: [false, false, false, false], repetitions: "4x12" },
        { name: "Pull over agarre prono", sessions: [false, false, false, false], repetitions: "4x15" },
        { name: "Curl en predicador con barra recta", sessions: [false, false, false, false], repetitions: "4x12" },
        { name: "Curl martillo parado", sessions: [false, false, false, false], repetitions: "12,10,8,8" },
        { name: "Antebrazo agarre supino con barra", sessions: [false, false, false, false], repetitions: "4x20" },
      ],
    },
    {
      day: 3,
      exercises: [
        { name: "Abducción y aducción", sessions: [false, false, false, false], repetitions: "4x15" },
        { name: "Curl femoral acostado", sessions: [false, false, false, false], repetitions: "12,10,10,8" },
        { name: "Peso muerto rumano con barra", sessions: [false, false, false, false], repetitions: "4x12" },
        { name: "Sentadilla tipo sumo", sessions: [false, false, false, false], repetitions: "15,12,10,10" },
        { name: "Patada en máquina", sessions: [false, false, false, false], repetitions: "4x15" },
        { name: "Remo al cuello con barra", sessions: [false, false, false, false], repetitions: "4x15" },
        { name: "Vuelos de pájaro sentado", sessions: [false, false, false, false], repetitions: "4x12" },
        { name: "Elevación lateral individual", sessions: [false, false, false, false], repetitions: "4x12" },
        { name: "Elevación de talón sentado", sessions: [false, false, false, false], repetitions: "4x20" },
      ],
    },
    {
      day: 4,
      exercises: [
        { name: "Crunches de rodilla en polea", sessions: [false, false, false, false], repetitions: "4x25" },
        { name: "Fondos en paralelas", sessions: [false, false, false, false], repetitions: "20,15,12,10" },
        { name: "Press plano con mancuernas", sessions: [false, false, false, false], repetitions: "12,10,10,8" },
        { name: "Press inclinado con barra", sessions: [false, false, false, false], repetitions: "12,10,10,8" },
        { name: "Fly en banco inclinado", sessions: [false, false, false, false], repetitions: "4x12" },
        { name: "Fly en cross over", sessions: [false, false, false, false], repetitions: "4x15" },
        { name: "Press francés en banco plano", sessions: [false, false, false, false], repetitions: "12,10,10,8" },
        { name: "Extensión de tríceps con lazo", sessions: [false, false, false, false], repetitions: "20,15,12,10" },
        { name: "Extensión de tríceps con barra V", sessions: [false, false, false, false], repetitions: "4x15" },
        { name: "Curl con barra recta agarre prono", sessions: [false, false, false, false], repetitions: "4x20" },
      ],
    },
  ];